on:
  schedule:
    - cron: '0 7 * * *'
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update -y
          sudo apt install -y qemu-user-static
      - uses: redhat-actions/buildah-build@v2
        with:
          image: codex
          tags: latest
          platforms: linux/amd64,linux/arm64
          containerfiles: |
            Containerfile
      - name: quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: codex
          tags: latest
          registry: quay.io/gmanka
          username: gmankab
          password: ${{ secrets.QUAY_TOKEN }}

